### PR TITLE
Apollo integration test

### PR DESCRIPTION
**Pull request by jeffkreeftmeijer**
Add an integration test for Apollo that calls an endpoint in a simple example application. 

Part of https://github.com/appsignal/appsignal-nodejs/issues/389.

### CODE REVIEW

**Comment by jeffkreeftmeijer** [comment]
This patch works locally, but runs into an issue checking the build matrix on CI. The build matrix is regenerated and produces a different result on my machine and on CI, even while using the exact same code with the exact same checksum.
I even added a Gemfile to make sure the Rake version matches, which didn't help, unsuprisingly.

[Removing the validation](https://appsignal.semaphoreci.com/workflows/39ea8a27-7a82-44b5-b01b-e0f5e0d9e2c3?pipeline_id=a9106a8b-3cf1-4df9-8cc8-bf501044a0d5) fixes the build. Or at least, gets past the first issue.

I need a second pair of eyes on this, so I’m leaving this pull request for now to focus on the other integration tests.

**Comment by tombruijn** [comment]
@jeffkreeftmeijer The validation fails because generating the semaphore.yml file will remove the `mono test --package=@appsignal/apollo-server` jobs. It can't find any Node.js/Jest test files, so it doesn't include jobs for those specs in the semaphore.yml file. Without those jobs it still includes the "extra_tests", which are the RSpec tests you wrote. I don't know how the other jobs were included unless it finds some Node.js test files on your machine locally.

Unless I missed something, regenerate the semaphore.yml file, commit it, and push it.

**Comment by jeffkreeftmeijer** [comment]
That makes sense, but I don’t think I have any extra tests lingering on my machine (my local checkout is in a clean state, as far as I can see). Could you regenerate the matrix and push it, if you have time? I’ll probably have time to take another look at this tomorrow.

**Comment by tombruijn** [comment]
@jeffkreeftmeijer Yes.

It [checks these two things](https://github.com/appsignal/appsignal-nodejs/blob/0dae939e8bc369c8f2b2d8d6a44bc71a4dd82e5f/Rakefile#L142-L143) so maybe you created a `__tests__` directory initially? Git won't check in an empty directory, but locally it will exist.

**Comment by tombruijn** [comment]
I improved the test files check in this PR: https://github.com/appsignal/appsignal-nodejs/pull/422

The build failure in this PR is caused by another issue.

**Comment by tombruijn** [comment]
Blocked on https://github.com/appsignal/appsignal-nodejs/pull/431

**Comment by tombruijn** [comment]
Closing in favor of #433

**Pull request closed without merging**
